language: node_js
node_js:
  - '8'
install:
  - npm install -g codecov nyc npx
  - npm install

script:
  - npm run lint
  - npm test

after_success:
  - npm run report-coverage

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run semantic-release
