language: node_js
node_js:
  - '8'
install:
  - npm install
  - mkdir tmp

cache:
  directories:
   - node_modules/opencv-build
   - node_modules/opencv4nodejs
   
script:
  - npm run lint
  - npm run doc
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run semantic-release
